	SELECT EMPCODE,SURNAME,OTHERNAMES,DESIG,EMPLOYEE.ORGANIZATIONUNITNAME,
	ISNULL(ORGANIZATIONUNITS.ORGANIZATIONUNITNAME,EMPLOYEE.ORGANIZATIONUNITNAME) AS PARENT,
termsid,gender,payroll_id,disengaged,paypoint_id,employee.ORGANIZATIONUNITcode
	FROM ALLDPTS 
	INNER JOIN ORGANIZATIONUNITS ON ORGANIZATIONUNITS.ORGANIZATIONUNITID=ALLDPTS.PARENTORGANIZATIONUNITID
	RIGHT OUTER JOIN EMPLOYEE ON EMPLOYEE.ORGANIZATIONUNITNAME=ALLDPTS.ORGANIZATIONUNITNAME
	ORDER BY PARENT	

select * from employee
select * from employees